### ISSUE TITLE
Create Page Styles for Snapshot

### ISSUE THREAD

**Issue by chair28980** [ShenaniganDApp/design#4]
Docs: https://docs.snapshot.org/spaces/add-skin

Create Shenanigan themed page stylings for https://snapshot.org/#/shedapp.eth

Reference Design docs (need link) for exact colors and styles.

**Comment by cheo0202** [comment]
Will this work as a feedback theme ???

**Comment by kittyslasher** [comment]
https://github.com/snapshot-labs/snapshot-spaces/pull/1152
![image.png](https://images.zenhubusercontent.com/607f5205d9b19b59a7e7445a/deec944f-ca40-412f-9b56-ca3935d121cf)
